import { test, expect } from '@playwright/test';
test('demo QR payment confirmation, admin verification and registration survive reload', async ({ page }) => {
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.route(/https:\/\/(images\.unsplash\.com|fonts\.(googleapis|gstatic)\.com)\//, route => route.abort());
  await page.goto('/login');
  await expect(page.getByText('Demo mode:', { exact: true })).toBeVisible();
  await page.getByLabel('Email', { exact: true }).fill('user@travelaura.com');
  await page.getByLabel('Password', { exact: true }).fill('demo');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page).toHaveURL(/my-bookings/);
  await page.goto('/booking/manali-adventure');
  await page.getByLabel('Travel date', { exact: true }).fill('2026-10-10');
  await page.getByLabel('Return date', { exact: true }).fill('2026-10-15');
  await page.getByPlaceholder('Coupon code').fill('WELCOME10');
  await page.getByRole('button', { name: 'Apply', exact: true }).click();
  await expect(page.getByText('Coupon WELCOME10 applied.')).toBeVisible();
  await page.getByRole('button', { name: 'Continue to payment' }).click();
  await expect(page).toHaveURL(/payment\//);
  const paymentUrl = page.url();
  await page.getByRole('button', { name: 'Submit payment confirmation' }).click();
  await expect(page.getByRole('heading', { name: 'Verification pending' })).toBeVisible();
  const submitted = await page.evaluate(() => JSON.parse(localStorage.getItem('travelaura_bookings'))[0]);
  expect(submitted).toMatchObject({ transactionId: '', paymentScreenshot: '', paymentStatus: 'pending', bookingStatus: 'pending' });
  expect(submitted.paymentSubmittedAt).toBeTruthy();
  await page.getByRole('button', { name: 'View my bookings' }).click();
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Manali Adventure Escape' })).toBeVisible();
  await page.goto('/admin');
  await expect(page).toHaveURL(/my-bookings/);
  await page.getByRole('button', { name: 'Sign out' }).click();
  await page.getByLabel('Email', { exact: true }).fill('admin@travelaura.com');
  await page.getByLabel('Password', { exact: true }).fill('demo');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page).toHaveURL(/admin$/);
  await expect(page.getByText('Confirmation submitted', { exact: true })).toBeVisible();
  await page.goto('/admin/bookings');
  await page.getByRole('button', { name: 'Approve payment' }).click();
  await expect(page.locator('.admin-booking .status-paid')).toHaveText('paid');
  await page.goto('/contact');
  await page.getByLabel('Name', { exact: true }).fill('Contact User');
  await page.getByLabel('Email', { exact: true }).fill('contact@example.test');
  await page.getByLabel('Message', { exact: true }).fill('Test message');
  await page.getByRole('button', { name: 'Send message' }).click();
  await expect(page.getByText('Thanks! Your message has been saved.')).toBeVisible();
  await page.goto('/my-bookings');
  await page.getByRole('button', { name: 'Sign out' }).click();
  await page.goto('/register');
  await page.getByLabel('Name', { exact: true }).fill('New Demo User');
  await page.getByLabel('Email', { exact: true }).fill('new-demo@example.test');
  await page.getByLabel('Phone', { exact: true }).fill('9876543210');
  await page.getByLabel('Password', { exact: true }).fill('password123');
  await page.getByLabel('Confirm password', { exact: true }).fill('password123');
  await page.getByRole('button', { name: 'Create account' }).click();
  await expect(page).toHaveURL(/packages$/);
  await page.goto(paymentUrl);
  await expect(page.getByText('Loading booking or booking unavailable.')).toBeVisible();
  assertNoErrors(errors);
});
function assertNoErrors(errors) { expect(errors).toEqual([]); }
